services:
  db:
   hostname: db
   image: postgres:alpine
   restart: always
   user: postgres
   environment:
     POSTGRES_USER: postgres
     POSTGRES_PASSWORD: password
     POSTGRES_DB: core
   ports:
     - 5432:5432
   expose:
     - 5432
   healthcheck:
     test: [ "CMD", "pg_isready" ]
     interval: 10s
     timeout: 5s
     retries: 5
#   volumes:
#     - ~/apps/postgres:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8000:8000
#  flyway:
#    image: boxfuse/flyway:5-alpine
#    command: -url=jdbc:postgresql://db:5432/core -schemas=public -user=postgres -password=password migrate
#    volumes:
#      - ./migration:/flyway/sql
#    depends_on:
#      db:
#        condition: service_healthy
